export {
  GraduationCap as AcademicCapIcon,
  ArrowLeft,
  ArrowRight,
  Menu as BurgerMenu,
  X as BurgerMenuOpened,
  Check,
  ChevronRight,
  MoveUpRight as ChevronUpRight,
  CircleAlert,
  Code as CodeIcon,
  Command as CommandIcon,
  Copy,
  Mail as Envelope,
  ExternalLink,
  FileText,
  Folder,
  Github,
  Gitlab,
  Heart as HeartIcon,
  Home as HomeIcon,
  Linkedin,
  Milestone,
  Search,
  Layers as SquareStack,
  Star,
  Wrench as ToolboxIcon,
  User as UserIcon,
  X as XIcon,
} from 'lucide-react';
